POST http://localhost:8080/students
Content-Type: application/json

{
  "name": "avatar",
  "age": 23
}

###
POST http://localhost:8080/faculties
Content-Type: application/json

{
  "name": "Slytherin",
  "color": "black"
}